on: [pull_request, push]
jobs:
  test:
    strategy:
      matrix:
        include:
          - platform: macos-latest
            python-min: "3.7"
          - platform: ubuntu-latest
            python-min: "3.6"
          - platform: windows-latest
            python-min: "3.6"
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: ${{matrix.python-min}}
      - uses: actions/setup-python@v1
        with:
          python-version: "3.10"
      - run: python -m pip install --upgrade tox
      - run: tox
